FROM ubuntu:18.04
MAINTAINER tom <stainer.tom@gmail.com>

# Build-time metadata as defined at http://label-schema.org
ARG PROJECT_NAME
ARG BUILD_DATE
ARG VCS_REF
ARG VERSION
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name="$PROJECT_NAME" \
      org.label-schema.description="Ubuntu docker image for epics-base" \
      org.label-schema.url="http://github.com/thomasms" \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url="https://github.com/thomasms" \
      org.label-schema.vendor="" \
      org.label-schema.version=$VERSION \
      org.label-schema.license="BSD-3-Clause" \
      org.label-schema.schema-version="1.0"

ENV PYTHONDONTWRITEBYTECODE 1.
ENV EPICS_BASE /epics/epics-base
ENV LD_LIBRARY_PATH ${EPICS_BASE}/lib

# Cannot get this to work in Dockerfile to persist over images
# Want export EPICS_ARCH=`perl ${EPICS_BASE}/startup/EpicsHostArch` but hard coded instead
ENV EPICS_ARCH linux-x86_64
ENV EPICS_BIN ${EPICS_BASE}/bin/${EPICS_ARCH}
ENV PATH ${PATH}:${EPICS_BIN}

COPY packages packages

# Install additional packages
RUN apt-get update -qq \
 && ln -sf /usr/share/zoneinfo/UTC /etc/localtime \
 && apt-get -y install $(cat packages) \
 && localedef -i en_US -f UTF-8 en_US.UTF-8 \
 && rm -rf /packages /var/lib/apt/lists/* \
# No python libs here - we should use venvs really
# && python3 -m pip install --upgrade pip \
# && python3 -m pip install numpy scipy pandas matplotlib epicscorelibs pvapy \
 && mkdir epics && cd epics && git clone --recursive -j4 https://github.com/thomasms/epics-base \
 && cd epics-base && make -j16 && find -maxdepth 1 -type d -not -name bin -not -name lib -not -name include -exec rm -rf {} \; rm * .*;

WORKDIR /

ENTRYPOINT /bin/bash

